# Auto-generated by infra/scripts/aws_ssm_sync.py
# DO NOT EDIT MANUALLY - Changes will be overwritten

# ECS task definition secrets configuration
# These reference AWS SSM Parameter Store secrets

# Secrets for demo environment
locals {
  ecs_secrets_demo = [
    {
      name      = "API_SECRET_KEY"
      valueFrom = "/genonaut/demo/API_SECRET_KEY"
    },
    {
      name      = "DATABASE_URL_TEST_INIT"
      valueFrom = "/genonaut/demo/DATABASE_URL_TEST_INIT"
    },
    {
      name      = "DB_PASSWORD_ADMIN"
      valueFrom = "/genonaut/demo/DB_PASSWORD_ADMIN"
    },
    {
      name      = "DB_PASSWORD_FOR_INIT"
      valueFrom = "/genonaut/demo/DB_PASSWORD_FOR_INIT"
    },
    {
      name      = "DB_PASSWORD_RO"
      valueFrom = "/genonaut/demo/DB_PASSWORD_RO"
    },
    {
      name      = "DB_PASSWORD_RW"
      valueFrom = "/genonaut/demo/DB_PASSWORD_RW"
    },
    {
      name      = "DB_USER_ADMIN_UUID"
      valueFrom = "/genonaut/demo/DB_USER_ADMIN_UUID"
    },
    {
      name      = "DEPLOY_AWS_ACCOUNT_ID"
      valueFrom = "/genonaut/demo/DEPLOY_AWS_ACCOUNT_ID"
    },
    {
      name      = "DEPLOY_AWS_PROFILE"
      valueFrom = "/genonaut/demo/DEPLOY_AWS_PROFILE"
    },
    {
      name      = "DEPLOY_AWS_REGION"
      valueFrom = "/genonaut/demo/DEPLOY_AWS_REGION"
    },
    {
      name      = "DEPLOY_TF_DYNAMO_DB_TABLE"
      valueFrom = "/genonaut/demo/DEPLOY_TF_DYNAMO_DB_TABLE"
    },
    {
      name      = "DEPLOY_TF_STATE_BUCKET_NAME"
      valueFrom = "/genonaut/demo/DEPLOY_TF_STATE_BUCKET_NAME"
    },
    {
      name      = "REDIS_PASSWORD"
      valueFrom = "/genonaut/demo/REDIS_PASSWORD"
    },
  ]
}

# Secrets for dev environment
locals {
  ecs_secrets_dev = [
    {
      name      = "API_SECRET_KEY"
      valueFrom = "/genonaut/dev/API_SECRET_KEY"
    },
    {
      name      = "DATABASE_URL_TEST_INIT"
      valueFrom = "/genonaut/dev/DATABASE_URL_TEST_INIT"
    },
    {
      name      = "DB_PASSWORD_ADMIN"
      valueFrom = "/genonaut/dev/DB_PASSWORD_ADMIN"
    },
    {
      name      = "DB_PASSWORD_FOR_INIT"
      valueFrom = "/genonaut/dev/DB_PASSWORD_FOR_INIT"
    },
    {
      name      = "DB_PASSWORD_RO"
      valueFrom = "/genonaut/dev/DB_PASSWORD_RO"
    },
    {
      name      = "DB_PASSWORD_RW"
      valueFrom = "/genonaut/dev/DB_PASSWORD_RW"
    },
    {
      name      = "DB_USER_ADMIN_UUID"
      valueFrom = "/genonaut/dev/DB_USER_ADMIN_UUID"
    },
    {
      name      = "DEPLOY_AWS_ACCOUNT_ID"
      valueFrom = "/genonaut/dev/DEPLOY_AWS_ACCOUNT_ID"
    },
    {
      name      = "DEPLOY_AWS_PROFILE"
      valueFrom = "/genonaut/dev/DEPLOY_AWS_PROFILE"
    },
    {
      name      = "DEPLOY_AWS_REGION"
      valueFrom = "/genonaut/dev/DEPLOY_AWS_REGION"
    },
    {
      name      = "DEPLOY_TF_DYNAMO_DB_TABLE"
      valueFrom = "/genonaut/dev/DEPLOY_TF_DYNAMO_DB_TABLE"
    },
    {
      name      = "DEPLOY_TF_STATE_BUCKET_NAME"
      valueFrom = "/genonaut/dev/DEPLOY_TF_STATE_BUCKET_NAME"
    },
    {
      name      = "REDIS_PASSWORD"
      valueFrom = "/genonaut/dev/REDIS_PASSWORD"
    },
  ]
}

# Secrets for prod environment
locals {
  ecs_secrets_prod = [
    {
      name      = "API_SECRET_KEY"
      valueFrom = "/genonaut/prod/API_SECRET_KEY"
    },
    {
      name      = "DATABASE_URL_TEST_INIT"
      valueFrom = "/genonaut/prod/DATABASE_URL_TEST_INIT"
    },
    {
      name      = "DB_PASSWORD_ADMIN"
      valueFrom = "/genonaut/prod/DB_PASSWORD_ADMIN"
    },
    {
      name      = "DB_PASSWORD_FOR_INIT"
      valueFrom = "/genonaut/prod/DB_PASSWORD_FOR_INIT"
    },
    {
      name      = "DB_PASSWORD_RO"
      valueFrom = "/genonaut/prod/DB_PASSWORD_RO"
    },
    {
      name      = "DB_PASSWORD_RW"
      valueFrom = "/genonaut/prod/DB_PASSWORD_RW"
    },
    {
      name      = "DB_USER_ADMIN_UUID"
      valueFrom = "/genonaut/prod/DB_USER_ADMIN_UUID"
    },
    {
      name      = "DEPLOY_AWS_ACCOUNT_ID"
      valueFrom = "/genonaut/prod/DEPLOY_AWS_ACCOUNT_ID"
    },
    {
      name      = "DEPLOY_AWS_PROFILE"
      valueFrom = "/genonaut/prod/DEPLOY_AWS_PROFILE"
    },
    {
      name      = "DEPLOY_AWS_REGION"
      valueFrom = "/genonaut/prod/DEPLOY_AWS_REGION"
    },
    {
      name      = "DEPLOY_TF_DYNAMO_DB_TABLE"
      valueFrom = "/genonaut/prod/DEPLOY_TF_DYNAMO_DB_TABLE"
    },
    {
      name      = "DEPLOY_TF_STATE_BUCKET_NAME"
      valueFrom = "/genonaut/prod/DEPLOY_TF_STATE_BUCKET_NAME"
    },
    {
      name      = "REDIS_PASSWORD"
      valueFrom = "/genonaut/prod/REDIS_PASSWORD"
    },
  ]
}

# Secrets for test environment
locals {
  ecs_secrets_test = [
    {
      name      = "API_SECRET_KEY"
      valueFrom = "/genonaut/test/API_SECRET_KEY"
    },
    {
      name      = "DATABASE_URL_TEST_INIT"
      valueFrom = "/genonaut/test/DATABASE_URL_TEST_INIT"
    },
    {
      name      = "DB_PASSWORD_ADMIN"
      valueFrom = "/genonaut/test/DB_PASSWORD_ADMIN"
    },
    {
      name      = "DB_PASSWORD_FOR_INIT"
      valueFrom = "/genonaut/test/DB_PASSWORD_FOR_INIT"
    },
    {
      name      = "DB_PASSWORD_RO"
      valueFrom = "/genonaut/test/DB_PASSWORD_RO"
    },
    {
      name      = "DB_PASSWORD_RW"
      valueFrom = "/genonaut/test/DB_PASSWORD_RW"
    },
    {
      name      = "DB_USER_ADMIN_UUID"
      valueFrom = "/genonaut/test/DB_USER_ADMIN_UUID"
    },
    {
      name      = "DEPLOY_AWS_ACCOUNT_ID"
      valueFrom = "/genonaut/test/DEPLOY_AWS_ACCOUNT_ID"
    },
    {
      name      = "DEPLOY_AWS_PROFILE"
      valueFrom = "/genonaut/test/DEPLOY_AWS_PROFILE"
    },
    {
      name      = "DEPLOY_AWS_REGION"
      valueFrom = "/genonaut/test/DEPLOY_AWS_REGION"
    },
    {
      name      = "DEPLOY_TF_DYNAMO_DB_TABLE"
      valueFrom = "/genonaut/test/DEPLOY_TF_DYNAMO_DB_TABLE"
    },
    {
      name      = "DEPLOY_TF_STATE_BUCKET_NAME"
      valueFrom = "/genonaut/test/DEPLOY_TF_STATE_BUCKET_NAME"
    },
    {
      name      = "REDIS_PASSWORD"
      valueFrom = "/genonaut/test/REDIS_PASSWORD"
    },
  ]
}
