"""GiST indexes

Revision ID: 09c47c15d4b1
Revises: 1aeaa46cbc42
Create Date: 2025-09-27 21:49:59.667864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c47c15d4b1'
down_revision: Union[str, Sequence[str], None] = '1aeaa46cbc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cgr_prompt_fts_idx'), table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index('cgr_prompt_fts_idx', 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english', coalesce(prompt, '') || ' ' || coalesce(negative_prompt, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cgr_prompt_fts_idx', table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index(op.f('cgr_prompt_fts_idx'), 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(prompt, ''::text) || ' '::text) || COALESCE(negative_prompt, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
