"""Add index on content_items_all.id

Revision ID: 18276283bb79
Revises: 5f699f3c7bbb
Create Date: 2025-11-08 18:01:24.283021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18276283bb79'
down_revision: Union[str, Sequence[str], None] = '5f699f3c7bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
