"""ComfyUI

Revision ID: 1842e4fee0fe
Revises: 94bcd3e6ce9d
Create Date: 2025-09-27 16:54:22.505168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1842e4fee0fe'
down_revision: Union[str, Sequence[str], None] = '94bcd3e6ce9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cgr_prompt_fts_idx'), table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index('cgr_prompt_fts_idx', 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english', coalesce(prompt, '') || ' ' || coalesce(negative_prompt, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cgr_prompt_fts_idx', table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index(op.f('cgr_prompt_fts_idx'), 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(prompt, ''::text) || ' '::text) || COALESCE(negative_prompt, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
