"""GiST indexes

Revision ID: 1aeaa46cbc42
Revises: 1842e4fee0fe
Create Date: 2025-09-27 21:48:23.915000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeaa46cbc42'
down_revision: Union[str, Sequence[str], None] = '1842e4fee0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cgr_prompt_fts_idx'), table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index('cgr_prompt_fts_idx', 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english', coalesce(prompt, '') || ' ' || coalesce(negative_prompt, ''))")], unique=False, postgresql_using='gin')
    op.create_index('idx_comfyui_gen_negative_prompt_gist', 'comfyui_generation_requests', ['negative_prompt'], unique=False, postgresql_using='gist', postgresql_ops={'negative_prompt': 'gist_trgm_ops'})
    op.create_index('idx_comfyui_gen_prompt_gist', 'comfyui_generation_requests', ['prompt'], unique=False, postgresql_using='gist', postgresql_ops={'prompt': 'gist_trgm_ops'})
    op.create_index('idx_content_items_title_gist', 'content_items', ['title'], unique=False, postgresql_using='gist', postgresql_ops={'title': 'gist_trgm_ops'})
    op.create_index('idx_content_items_auto_title_gist', 'content_items_auto', ['title'], unique=False, postgresql_using='gist', postgresql_ops={'title': 'gist_trgm_ops'})
    op.create_index('idx_generation_jobs_prompt_gist', 'generation_jobs', ['prompt'], unique=False, postgresql_using='gist', postgresql_ops={'prompt': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_generation_jobs_prompt_gist', table_name='generation_jobs', postgresql_using='gist', postgresql_ops={'prompt': 'gist_trgm_ops'})
    op.drop_index('idx_content_items_auto_title_gist', table_name='content_items_auto', postgresql_using='gist', postgresql_ops={'title': 'gist_trgm_ops'})
    op.drop_index('idx_content_items_title_gist', table_name='content_items', postgresql_using='gist', postgresql_ops={'title': 'gist_trgm_ops'})
    op.drop_index('idx_comfyui_gen_prompt_gist', table_name='comfyui_generation_requests', postgresql_using='gist', postgresql_ops={'prompt': 'gist_trgm_ops'})
    op.drop_index('idx_comfyui_gen_negative_prompt_gist', table_name='comfyui_generation_requests', postgresql_using='gist', postgresql_ops={'negative_prompt': 'gist_trgm_ops'})
    op.drop_index('cgr_prompt_fts_idx', table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index(op.f('cgr_prompt_fts_idx'), 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(prompt, ''::text) || ' '::text) || COALESCE(negative_prompt, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
