"""

Revision ID: 20aad43c6683
Revises: ec47a6ae1d27
Create Date: 2025-10-16 20:30:58.499051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aad43c6683'
down_revision: Union[str, Sequence[str], None] = 'ec47a6ae1d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_search_history_user_query', 'user_search_history', ['user_id', 'search_query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_search_history_user_query', table_name='user_search_history')
    # ### end Alembic commands ###
