"""add tag cardinality stats table

Revision ID: 35129ad8b067
Revises: dacc34ed987b
Create Date: 2025-10-20 13:50:10.722597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35129ad8b067'
down_revision: Union[str, Sequence[str], None] = 'dacc34ed987b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_cardinality_stats',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('content_source', sa.String(length=10), nullable=False),
    sa.Column('cardinality', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'content_source')
    )
    op.create_index('idx_tag_cardinality_stats_tag_src', 'tag_cardinality_stats', ['tag_id', 'content_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_cardinality_stats_tag_src', table_name='tag_cardinality_stats')
    op.drop_table('tag_cardinality_stats')
    # ### end Alembic commands ###
