"""add gen_source_stats table for caching content counts

Revision ID: 40cbad89bb54
Revises: 0a277157bd85
Create Date: 2025-10-22 00:15:25.966153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cbad89bb54'
down_revision: Union[str, Sequence[str], None] = '0a277157bd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_source_stats',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'source_type')
    )
    op.create_index('idx_gen_source_stats_community', 'gen_source_stats', ['source_type'], unique=False, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('idx_gen_source_stats_user_src', 'gen_source_stats', ['user_id', 'source_type'], unique=False)
    op.create_index('idx_content_items_created_at_desc', 'content_items', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_type_created', 'content_items', ['content_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_created_at_desc', 'content_items_auto', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_type_created', 'content_items_auto', ['content_type', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_items_auto_type_created', table_name='content_items_auto')
    op.drop_index('idx_content_items_auto_created_at_desc', table_name='content_items_auto')
    op.drop_index('idx_content_items_type_created', table_name='content_items')
    op.drop_index('idx_content_items_created_at_desc', table_name='content_items')
    op.drop_index('idx_gen_source_stats_user_src', table_name='gen_source_stats')
    op.drop_index('idx_gen_source_stats_community', table_name='gen_source_stats', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_table('gen_source_stats')
    # ### end Alembic commands ###
