"""

Revision ID: 4a01b4c88542
Revises: 86456c44a065
Create Date: 2025-10-18 10:25:44.861055

FYIs: Why did make migrate-prep create an empty migration (and only once)?
- context: We were having trouble with some botched migrations and probably ended up deleting one as well, 
  creating the revision mismatch.

LLM (https://chatgpt.com/g/g-p-68f1d7b5c86c819183c4578c779d151c/c/68ca0c52-7c18-8321-8689-fc5350351e25) said:
> No diffs to apply: Autogenerate compares Base.metadata vs the DB. If they match, you get a pass migration.
> Your new include_object filter: You excluded the partition parent and special indexes, so Alembic won’t try to 
  drop/recreate them. Result: no diffs → empty file.
> “Target database is not up to date” earlier: you deleted 943c18761d04_.py, but the DB was still stamped at that 
  rev. Until you upgrade/stamp the DB to match the on-disk head, Alembic blocks revision. Once you ran make 
  migrate-demo; make migrate-test, you realigned, so migrate-prep could run again.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a01b4c88542'
down_revision: Union[str, Sequence[str], None] = '86456c44a065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
