"""Add tags as UUID array

Revision ID: 4f847fa892af
Revises: f107731c3074
Create Date: 2025-10-13 00:36:43.061947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f847fa892af'
down_revision: Union[str, Sequence[str], None] = 'f107731c3074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new tags columns as UUID arrays with empty array default
    # Will be populated by backfill script in next phase
    op.add_column('content_items', sa.Column('tags', sa.ARRAY(sa.UUID()), nullable=False, server_default="{}"))
    op.add_column('content_items_auto', sa.Column('tags', sa.ARRAY(sa.UUID()), nullable=False, server_default="{}"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items_auto', 'tags')
    op.drop_column('content_items', 'tags')
    # ### end Alembic commands ###
