"""Add route_analytics and route_analytics_hourly tables

Revision ID: 564cc0b09f6c
Revises: a8516cb4ecd4
Create Date: 2025-10-23 16:11:02.328548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '564cc0b09f6c'
down_revision: Union[str, Sequence[str], None] = 'a8516cb4ecd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_analytics_hourly',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('query_params_normalized', JSONB(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('client_errors', sa.Integer(), nullable=False),
    sa.Column('server_errors', sa.Integer(), nullable=False),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=True),
    sa.Column('p50_duration_ms', sa.Integer(), nullable=True),
    sa.Column('p95_duration_ms', sa.Integer(), nullable=True),
    sa.Column('p99_duration_ms', sa.Integer(), nullable=True),
    sa.Column('unique_users', sa.Integer(), nullable=True),
    sa.Column('avg_request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('avg_response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('avg_db_query_count', sa.Float(), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('cache_misses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'route', 'method', 'query_params_normalized', name='uq_route_analytics_hourly_time_route_params')
    )
    op.create_index('idx_route_metrics_duration', 'route_analytics_hourly', [sa.literal_column('avg_duration_ms DESC')], unique=False)
    op.create_index('idx_route_metrics_route_time', 'route_analytics_hourly', ['route', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_route_metrics_timestamp', 'route_analytics_hourly', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_route_metrics_total_requests', 'route_analytics_hourly', [sa.literal_column('total_requests DESC')], unique=False)
    op.create_index(op.f('ix_route_analytics_hourly_timestamp'), 'route_analytics_hourly', ['timestamp'], unique=False)
    op.create_table('route_analytics',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=False),
    sa.Column('query_params', JSONB(), nullable=True),
    sa.Column('query_params_normalized', JSONB(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('db_query_count', sa.Integer(), nullable=True),
    sa.Column('cache_status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_analytics_duration', 'route_analytics', [sa.literal_column('duration_ms DESC')], unique=False)
    op.create_index('idx_route_analytics_route_time', 'route_analytics', ['route', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_route_analytics_timestamp', 'route_analytics', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('idx_route_analytics_user_time', 'route_analytics', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_route_analytics_route'), 'route_analytics', ['route'], unique=False)
    op.create_index(op.f('ix_route_analytics_timestamp'), 'route_analytics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_analytics_timestamp'), table_name='route_analytics')
    op.drop_index(op.f('ix_route_analytics_route'), table_name='route_analytics')
    op.drop_index('idx_route_analytics_user_time', table_name='route_analytics')
    op.drop_index('idx_route_analytics_timestamp', table_name='route_analytics')
    op.drop_index('idx_route_analytics_route_time', table_name='route_analytics')
    op.drop_index('idx_route_analytics_duration', table_name='route_analytics')
    op.drop_table('route_analytics')
    op.drop_index(op.f('ix_route_analytics_hourly_timestamp'), table_name='route_analytics_hourly')
    op.drop_index('idx_route_metrics_total_requests', table_name='route_analytics_hourly')
    op.drop_index('idx_route_metrics_timestamp', table_name='route_analytics_hourly')
    op.drop_index('idx_route_metrics_route_time', table_name='route_analytics_hourly')
    op.drop_index('idx_route_metrics_duration', table_name='route_analytics_hourly')
    op.drop_table('route_analytics_hourly')
    # ### end Alembic commands ###
