"""add_user_notifications_table

Revision ID: 5a60e1e257d3
Revises: 1db7203ecfa3
Create Date: 2025-10-04 03:06:53.459357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a60e1e257d3'
down_revision: Union[str, Sequence[str], None] = '1db7203ecfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('related_content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['related_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_type', 'user_notifications', ['notification_type'], unique=False)
    op.create_index('idx_notifications_user_created', 'user_notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_notifications_user_unread', 'user_notifications', ['user_id', 'read_status'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_read_status'), 'user_notifications', ['read_status'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_read_status'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index('idx_notifications_user_unread', table_name='user_notifications')
    op.drop_index('idx_notifications_user_created', table_name='user_notifications')
    op.drop_index('idx_notifications_type', table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
