"""content id seq

Revision ID: 5f699f3c7bbb
Revises: 672c99981361
Create Date: 2025-11-08 17:38:19.186883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f699f3c7bbb'
down_revision: Union[str, Sequence[str], None] = '672c99981361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to use shared sequence across content_items partitions.

    This migration:
    1. Drops IDENTITY constraints from both partition tables (if they exist)
    2. Creates a shared sequence for globally unique IDs
    3. Sets DEFAULT on both tables to use the shared sequence

    Note: This migration is idempotent and safe to run on databases that
    have already been manually migrated.
    """
    # Drop IDENTITY constraints if they exist
    # This is necessary because IDENTITY columns can't have their DEFAULT changed
    op.execute('ALTER TABLE content_items ALTER COLUMN id DROP IDENTITY IF EXISTS')
    op.execute('ALTER TABLE content_items_auto ALTER COLUMN id DROP IDENTITY IF EXISTS')

    # Create shared sequence if it doesn't exist
    # Start at 3000000 to be well above any existing IDs
    op.execute('CREATE SEQUENCE IF NOT EXISTS content_items_id_seq START WITH 3000000')

    # Grant permissions on sequence
    op.execute('GRANT USAGE, SELECT ON SEQUENCE content_items_id_seq TO PUBLIC')

    # Set DEFAULT to use shared sequence for both tables
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
