"""

Revision ID: 744bd1dd2875
Revises: 8431b8b40b09
Create Date: 2025-10-22 13:05:28.147592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744bd1dd2875'
down_revision: Union[str, Sequence[str], None] = '8431b8b40b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_source_stats', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, cycle=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_source_stats', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False)
    # ### end Alembic commands ###
