"""Integer PKs: Serial to Identity

Revision ID: 7d2da1f1decd
Revises: a1ea0752d265
Create Date: 2025-10-18 10:48:27.416875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2da1f1decd'
down_revision: Union[str, Sequence[str], None] = 'a1ea0752d265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_models', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('content_tags', 'content_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False)
    op.alter_column('flagged_content', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recommendations', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tag_ratings', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_interactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_notifications', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_search_history', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_search_history', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_notifications', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_interactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tag_ratings', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recommendations', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flagged_content', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('content_tags', 'content_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('available_models', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
