"""Add prompt field with immutability triggers

Revision ID: 8ce127680ba3
Revises: 25f74da059a2
Create Date: 2025-10-01 21:59:35.721725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce127680ba3'
down_revision: Union[str, Sequence[str], None] = '25f74da059a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cgr_prompt_fts_idx'), table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index('cgr_prompt_fts_idx', 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english', coalesce(prompt, '') || ' ' || coalesce(negative_prompt, ''))")], unique=False, postgresql_using='gin')

    # Add prompt column to content_items with nullable=True and temporary default
    op.add_column('content_items', sa.Column('prompt', sa.String(length=20000), nullable=True, server_default=sa.text("'todo'")))
    # Backfill any pre-existing NULLs
    op.execute("UPDATE content_items SET prompt = 'todo' WHERE prompt IS NULL")
    # Enforce NOT NULL
    op.alter_column('content_items', 'prompt', nullable=False)
    # Drop the default so future inserts must provide a value
    op.alter_column('content_items', 'prompt', server_default=None)

    # Add prompt column to content_items_auto with nullable=True and temporary default
    op.add_column('content_items_auto', sa.Column('prompt', sa.String(length=20000), nullable=True, server_default=sa.text("'todo'")))
    # Backfill any pre-existing NULLs
    op.execute("UPDATE content_items_auto SET prompt = 'todo' WHERE prompt IS NULL")
    # Enforce NOT NULL
    op.alter_column('content_items_auto', 'prompt', nullable=False)
    # Drop the default so future inserts must provide a value
    op.alter_column('content_items_auto', 'prompt', server_default=None)

    # Alter generation_jobs.prompt from TEXT to String(20000)
    # This column already exists and is NOT NULL, so we don't need backfill logic
    op.alter_column('generation_jobs', 'prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generation_jobs', 'prompt',
               existing_type=sa.String(length=20000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('content_items_auto', 'prompt')
    op.drop_column('content_items', 'prompt')
    op.drop_index('cgr_prompt_fts_idx', table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index(op.f('cgr_prompt_fts_idx'), 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(prompt, ''::text) || ' '::text) || COALESCE(negative_prompt, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
