"""

Revision ID: 94c538597cde
Revises: 0a277157bd85
Create Date: 2025-10-22 01:08:22.677765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94c538597cde'
down_revision: Union[str, Sequence[str], None] = '0a277157bd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create gen_source_stats table if it doesn't exist
    # This fixes the migration ordering issue where table was created manually
    # Note: Using GENERATED BY DEFAULT (not ALWAYS) to match schema.py
    op.execute("""
        CREATE TABLE IF NOT EXISTS gen_source_stats (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID REFERENCES users(id) ON DELETE CASCADE,
            source_type VARCHAR(10) NOT NULL,
            count INTEGER NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )
    """)

    # Create partial unique indexes for gen_source_stats
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_gen_source_stats_community
        ON gen_source_stats (source_type) WHERE user_id IS NULL
    """)

    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_gen_source_stats_user_src
        ON gen_source_stats (user_id, source_type) WHERE user_id IS NOT NULL
    """)

    op.create_index('idx_content_items_created_at_desc', 'content_items', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_type_created', 'content_items', ['content_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_created_at_desc', 'content_items_auto', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_type_created', 'content_items_auto', ['content_type', sa.literal_column('created_at DESC')], unique=False)

    # Note: ALTER commands removed - table is created with correct settings above
    # If table already exists from manual creation, it should work as-is
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_source_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('gen_source_stats', 'count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('gen_source_stats', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False)
    op.drop_index('idx_content_items_auto_type_created', table_name='content_items_auto')
    op.drop_index('idx_content_items_auto_created_at_desc', table_name='content_items_auto')
    op.drop_index('idx_content_items_type_created', table_name='content_items')
    op.drop_index('idx_content_items_created_at_desc', table_name='content_items')
    # ### end Alembic commands ###
