"""add_is_private_to_content_items

Revision ID: 965558fecc0b
Revises: 27154362fa82
Create Date: 2025-09-19 16:50:10.623643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965558fecc0b'
down_revision: Union[str, Sequence[str], None] = '27154362fa82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('is_private', sa.Boolean(), nullable=False, server_default='false'))
    # Note: The indexes ci_title_fts_idx and gj_prompt_fts_idx already exist from migration 27154362fa82
    # No need to drop non-existent indexes or recreate existing ones
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'is_private')
    # Note: The indexes ci_title_fts_idx and gj_prompt_fts_idx should remain as they were created
    # in migration 27154362fa82 and are not part of this migration's changes
    # ### end Alembic commands ###
