"""add_is_private_to_content_items

Revision ID: 965558fecc0b
Revises: 27154362fa82
Create Date: 2025-09-19 16:50:10.623643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965558fecc0b'
down_revision: Union[str, Sequence[str], None] = '27154362fa82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('is_private', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index(op.f('ix_content_items_title_fts'), table_name='content_items', postgresql_using='gin')
    op.create_index('ci_title_fts_idx', 'content_items', [sa.literal_column("to_tsvector('english', coalesce(title, ''))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_generation_jobs_prompt_fts'), table_name='generation_jobs', postgresql_using='gin')
    op.create_index('gj_prompt_fts_idx', 'generation_jobs', [sa.literal_column("to_tsvector('english', coalesce(prompt, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gj_prompt_fts_idx', table_name='generation_jobs', postgresql_using='gin')
    op.create_index(op.f('ix_generation_jobs_prompt_fts'), 'generation_jobs', [sa.literal_column("to_tsvector('english'::regconfig, prompt)")], unique=False, postgresql_using='gin')
    op.drop_index('ci_title_fts_idx', table_name='content_items', postgresql_using='gin')
    op.create_index(op.f('ix_content_items_title_fts'), 'content_items', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.drop_column('content_items', 'is_private')
    # ### end Alembic commands ###
