"""merge_generation_tables_celery_integration

Revision ID: 9872ef1e50c3
Revises: 704ba727e23b
Create Date: 2025-10-03 17:55:03.210908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9872ef1e50c3'
down_revision: Union[str, Sequence[str], None] = '704ba727e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cgr_prompt_fts_idx'), table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index('cgr_prompt_fts_idx', 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english', coalesce(prompt, '') || ' ' || coalesce(negative_prompt, ''))")], unique=False, postgresql_using='gin')
    op.add_column('generation_jobs', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generation_jobs', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('generation_jobs', sa.Column('negative_prompt', sa.Text(), nullable=True))
    op.add_column('generation_jobs', sa.Column('checkpoint_model', sa.String(length=255), nullable=True))
    op.add_column('generation_jobs', sa.Column('lora_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generation_jobs', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('batch_size', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('comfyui_prompt_id', sa.String(length=255), nullable=True))
    op.create_index('idx_generation_jobs_celery_task_id', 'generation_jobs', ['celery_task_id'], unique=False, postgresql_where=sa.text('celery_task_id IS NOT NULL'))
    op.create_index('idx_generation_jobs_comfyui_prompt_id', 'generation_jobs', ['comfyui_prompt_id'], unique=False, postgresql_where=sa.text('comfyui_prompt_id IS NOT NULL'))
    op.create_index(op.f('ix_generation_jobs_celery_task_id'), 'generation_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_comfyui_prompt_id'), 'generation_jobs', ['comfyui_prompt_id'], unique=False)
    op.drop_constraint(op.f('generation_jobs_result_content_id_fkey'), 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'generation_jobs', 'content_items', ['content_id'], ['id'])
    op.drop_column('generation_jobs', 'parameters')
    op.drop_column('generation_jobs', 'result_content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('result_content_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generation_jobs', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('generation_jobs_result_content_id_fkey'), 'generation_jobs', 'content_items', ['result_content_id'], ['id'])
    op.drop_index(op.f('ix_generation_jobs_comfyui_prompt_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_celery_task_id'), table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_comfyui_prompt_id', table_name='generation_jobs', postgresql_where=sa.text('comfyui_prompt_id IS NOT NULL'))
    op.drop_index('idx_generation_jobs_celery_task_id', table_name='generation_jobs', postgresql_where=sa.text('celery_task_id IS NOT NULL'))
    op.drop_column('generation_jobs', 'comfyui_prompt_id')
    op.drop_column('generation_jobs', 'batch_size')
    op.drop_column('generation_jobs', 'height')
    op.drop_column('generation_jobs', 'width')
    op.drop_column('generation_jobs', 'lora_models')
    op.drop_column('generation_jobs', 'checkpoint_model')
    op.drop_column('generation_jobs', 'negative_prompt')
    op.drop_column('generation_jobs', 'celery_task_id')
    op.drop_column('generation_jobs', 'content_id')
    op.drop_column('generation_jobs', 'params')
    op.drop_index('cgr_prompt_fts_idx', table_name='comfyui_generation_requests', postgresql_using='gin')
    op.create_index(op.f('cgr_prompt_fts_idx'), 'comfyui_generation_requests', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(prompt, ''::text) || ' '::text) || COALESCE(negative_prompt, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
