"""Update FK constraints for content deletion cascades

Revision ID: b4f6d6bbfb89
Revises: c43685065143
Create Date: 2025-11-16 16:07:20.800877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f6d6bbfb89'
down_revision: Union[str, Sequence[str], None] = 'c43685065143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookmark_category_cover_content'), 'bookmark_categories', type_='foreignkey')
    op.create_foreign_key('fk_bookmark_category_cover_content', 'bookmark_categories', 'content_items_all', ['cover_content_id', 'cover_content_source_type'], ['id', 'source_type'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_bookmark_content'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key('fk_bookmark_content', 'bookmarks', 'content_items_all', ['content_id', 'content_source_type'], ['id', 'source_type'], ondelete='CASCADE')
    op.drop_constraint('generation_jobs_content_id_fkey', 'generation_jobs', type_='foreignkey')
    op.create_foreign_key('generation_jobs_content_id_fkey', 'generation_jobs', 'content_items', ['content_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recommendations', 'content_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('recommendations_content_item_id_fkey'), 'recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'recommendations', 'content_items', ['content_item_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_interactions', 'content_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('user_interactions_content_item_id_fkey'), 'user_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_interactions', 'content_items', ['content_item_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_notifications_related_content_id_fkey'), 'user_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_notifications', 'content_items', ['related_content_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.create_foreign_key(op.f('user_notifications_related_content_id_fkey'), 'user_notifications', 'content_items', ['related_content_id'], ['id'])
    op.drop_constraint('generation_jobs_content_id_fkey', 'generation_jobs', type_='foreignkey')
    op.create_foreign_key('generation_jobs_content_id_fkey', 'generation_jobs', 'content_items', ['content_id'], ['id'])
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('user_interactions_content_item_id_fkey'), 'user_interactions', 'content_items', ['content_item_id'], ['id'])
    op.alter_column('user_interactions', 'content_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('recommendations_content_item_id_fkey'), 'recommendations', 'content_items', ['content_item_id'], ['id'])
    op.alter_column('recommendations', 'content_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_bookmark_content', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookmark_content'), 'bookmarks', 'content_items_all', ['content_id', 'content_source_type'], ['id', 'source_type'])
    op.drop_constraint('fk_bookmark_category_cover_content', 'bookmark_categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bookmark_category_cover_content'), 'bookmark_categories', 'content_items_all', ['cover_content_id', 'cover_content_source_type'], ['id', 'source_type'])
    # ### end Alembic commands ###
