"""bookmarks

Revision ID: c43685065143
Revises: 18276283bb79
Create Date: 2025-11-11 21:04:35.147201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43685065143'
down_revision: Union[str, Sequence[str], None] = '18276283bb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('cover_content_id', sa.BigInteger(), nullable=True),
    sa.Column('cover_content_source_type', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_content_id', 'cover_content_source_type'], ['content_items_all.id', 'content_items_all.source_type'], name='fk_bookmark_category_cover_content'),
    sa.ForeignKeyConstraint(['parent_id', 'user_id'], ['bookmark_categories.id', 'bookmark_categories.user_id'], name='fk_bookmark_category_parent_same_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_bookmark_category_id_user'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('user_id', 'name', 'parent_id', name='uq_bookmark_category_user_name_parent')
    )
    op.create_index('idx_bookmark_categories_parent', 'bookmark_categories', ['parent_id'], unique=False)
    op.create_index('idx_bookmark_categories_share_token', 'bookmark_categories', ['share_token'], unique=False)
    op.create_index('idx_bookmark_categories_user_created', 'bookmark_categories', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_bookmark_categories_user_sort', 'bookmark_categories', ['user_id', 'sort_index'], unique=False)
    op.create_index(op.f('ix_bookmark_categories_user_id'), 'bookmark_categories', ['user_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('content_source_type', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id', 'content_source_type'], ['content_items_all.id', 'content_items_all.source_type'], name='fk_bookmark_content'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_bookmark_id_user'),
    sa.UniqueConstraint('user_id', 'content_id', 'content_source_type', name='uq_bookmark_user_content')
    )
    op.create_index('idx_bookmarks_content', 'bookmarks', ['content_id', 'content_source_type'], unique=False)
    op.create_index('idx_bookmarks_is_public', 'bookmarks', ['is_public'], unique=False)
    op.create_index('idx_bookmarks_user_created', 'bookmarks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_bookmarks_user_not_deleted', 'bookmarks', ['user_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_bookmarks_user_pinned', 'bookmarks', ['user_id', 'pinned', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_bookmarks_content_id'), 'bookmarks', ['content_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('bookmark_category_members',
    sa.Column('bookmark_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id', 'user_id'], ['bookmarks.id', 'bookmarks.user_id'], name='fk_bookmark_member_bookmark_same_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id', 'user_id'], ['bookmark_categories.id', 'bookmark_categories.user_id'], name='fk_bookmark_member_category_same_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'category_id')
    )
    op.create_index('idx_bookmark_members_bookmark', 'bookmark_category_members', ['bookmark_id'], unique=False)
    op.create_index('idx_bookmark_members_category', 'bookmark_category_members', ['category_id'], unique=False)
    op.create_index('idx_bookmark_members_user', 'bookmark_category_members', ['user_id'], unique=False)
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_items_auto', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    op.alter_column('content_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('content_items_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_index('idx_bookmark_members_user', table_name='bookmark_category_members')
    op.drop_index('idx_bookmark_members_category', table_name='bookmark_category_members')
    op.drop_index('idx_bookmark_members_bookmark', table_name='bookmark_category_members')
    op.drop_table('bookmark_category_members')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_content_id'), table_name='bookmarks')
    op.drop_index('idx_bookmarks_user_pinned', table_name='bookmarks')
    op.drop_index('idx_bookmarks_user_not_deleted', table_name='bookmarks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_bookmarks_user_created', table_name='bookmarks')
    op.drop_index('idx_bookmarks_is_public', table_name='bookmarks')
    op.drop_index('idx_bookmarks_content', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_bookmark_categories_user_id'), table_name='bookmark_categories')
    op.drop_index('idx_bookmark_categories_user_sort', table_name='bookmark_categories')
    op.drop_index('idx_bookmark_categories_user_created', table_name='bookmark_categories')
    op.drop_index('idx_bookmark_categories_share_token', table_name='bookmark_categories')
    op.drop_index('idx_bookmark_categories_parent', table_name='bookmark_categories')
    op.drop_table('bookmark_categories')
    # ### end Alembic commands ###
