"""

Revision ID: cad9b90762d9
Revises: c824e7b526be
Create Date: 2025-09-23 23:18:27.745619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad9b90762d9'
down_revision: Union[str, Sequence[str], None] = 'c824e7b526be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_content_items_created_at_desc', 'content_items', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_creator_created', 'content_items', ['creator_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_metadata_gin', 'content_items', ['item_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_items_public_created', 'content_items', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_private = false'))
    op.create_index('idx_content_items_quality_created', 'content_items', [sa.literal_column('quality_score DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_tags_gin', 'content_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_items_type_created', 'content_items', ['content_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_created_at_desc', 'content_items_auto', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_creator_created', 'content_items_auto', ['creator_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_metadata_gin', 'content_items_auto', ['item_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_items_auto_public_created', 'content_items_auto', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_private = false'))
    op.create_index('idx_content_items_auto_quality_created', 'content_items_auto', [sa.literal_column('quality_score DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_content_items_auto_tags_gin', 'content_items_auto', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_items_auto_type_created', 'content_items_auto', ['content_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_completed_at_desc', 'generation_jobs', [sa.literal_column('completed_at DESC')], unique=False, postgresql_where=sa.text('completed_at IS NOT NULL'))
    op.create_index('idx_generation_jobs_created_at_desc', 'generation_jobs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_status_created', 'generation_jobs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_status_created_priority', 'generation_jobs', ['status', sa.literal_column('created_at ASC')], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('idx_generation_jobs_type_created', 'generation_jobs', ['job_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_user_created', 'generation_jobs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_user_status_created', 'generation_jobs', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_generation_jobs_user_type_created', 'generation_jobs', ['user_id', 'job_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_algorithm_created', 'recommendations', ['algorithm_version', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_content_created', 'recommendations', ['content_item_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_created_at_desc', 'recommendations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_score_created', 'recommendations', [sa.literal_column('recommendation_score DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_served_created', 'recommendations', ['is_served', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_user_created', 'recommendations', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_user_score_created', 'recommendations', ['user_id', sa.literal_column('recommendation_score DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_recommendations_user_served_created', 'recommendations', ['user_id', 'is_served', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_interactions_content_created', 'user_interactions', ['content_item_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_interactions_created_at_desc', 'user_interactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_interactions_rating_created', 'user_interactions', [sa.literal_column('rating DESC'), sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('rating IS NOT NULL'))
    op.create_index('idx_user_interactions_type_created', 'user_interactions', ['interaction_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_interactions_user_created', 'user_interactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_interactions_user_type_created', 'user_interactions', ['user_id', 'interaction_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_active_created', 'users', ['is_active', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_created_at_desc', 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=False)
    op.create_index('idx_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username_lower', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_created_at_desc', table_name='users')
    op.drop_index('idx_users_active_created', table_name='users')
    op.drop_index('idx_user_interactions_user_type_created', table_name='user_interactions')
    op.drop_index('idx_user_interactions_user_created', table_name='user_interactions')
    op.drop_index('idx_user_interactions_type_created', table_name='user_interactions')
    op.drop_index('idx_user_interactions_rating_created', table_name='user_interactions', postgresql_where=sa.text('rating IS NOT NULL'))
    op.drop_index('idx_user_interactions_created_at_desc', table_name='user_interactions')
    op.drop_index('idx_user_interactions_content_created', table_name='user_interactions')
    op.drop_index('idx_recommendations_user_served_created', table_name='recommendations')
    op.drop_index('idx_recommendations_user_score_created', table_name='recommendations')
    op.drop_index('idx_recommendations_user_created', table_name='recommendations')
    op.drop_index('idx_recommendations_served_created', table_name='recommendations')
    op.drop_index('idx_recommendations_score_created', table_name='recommendations')
    op.drop_index('idx_recommendations_created_at_desc', table_name='recommendations')
    op.drop_index('idx_recommendations_content_created', table_name='recommendations')
    op.drop_index('idx_recommendations_algorithm_created', table_name='recommendations')
    op.drop_index('idx_generation_jobs_user_type_created', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_user_status_created', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_user_created', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_type_created', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_status_created_priority', table_name='generation_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index('idx_generation_jobs_status_created', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_created_at_desc', table_name='generation_jobs')
    op.drop_index('idx_generation_jobs_completed_at_desc', table_name='generation_jobs', postgresql_where=sa.text('completed_at IS NOT NULL'))
    op.drop_index('idx_content_items_auto_type_created', table_name='content_items_auto')
    op.drop_index('idx_content_items_auto_tags_gin', table_name='content_items_auto', postgresql_using='gin')
    op.drop_index('idx_content_items_auto_quality_created', table_name='content_items_auto')
    op.drop_index('idx_content_items_auto_public_created', table_name='content_items_auto', postgresql_where=sa.text('is_private = false'))
    op.drop_index('idx_content_items_auto_metadata_gin', table_name='content_items_auto', postgresql_using='gin')
    op.drop_index('idx_content_items_auto_creator_created', table_name='content_items_auto')
    op.drop_index('idx_content_items_auto_created_at_desc', table_name='content_items_auto')
    op.drop_index('idx_content_items_type_created', table_name='content_items')
    op.drop_index('idx_content_items_tags_gin', table_name='content_items', postgresql_using='gin')
    op.drop_index('idx_content_items_quality_created', table_name='content_items')
    op.drop_index('idx_content_items_public_created', table_name='content_items', postgresql_where=sa.text('is_private = false'))
    op.drop_index('idx_content_items_metadata_gin', table_name='content_items', postgresql_using='gin')
    op.drop_index('idx_content_items_creator_created', table_name='content_items')
    op.drop_index('idx_content_items_created_at_desc', table_name='content_items')
    # ### end Alembic commands ###
