"""add index for pre-JOIN tag filtering

Revision ID: dacc34ed987b
Revises: eb4d0ebbd211
Create Date: 2025-10-20 13:46:36.732689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacc34ed987b'
down_revision: Union[str, Sequence[str], None] = 'eb4d0ebbd211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_content_tags_tag_src_content', 'content_tags', ['tag_id', 'content_source', 'content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_tags_tag_src_content', table_name='content_tags')
    # ### end Alembic commands ###
