"""Add source_type generated column for partitioning

Revision ID: e7526785bd0d
Revises: 7180a61da3d5
Create Date: 2025-10-18 04:22:34.168445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7526785bd0d'
down_revision: Union[str, Sequence[str], None] = '7180a61da3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add source_type columns for partition key
    # These are regular columns with DEFAULT values (not GENERATED)
    # PostgreSQL partitioning doesn't allow generated columns in child tables
    op.execute("""
        ALTER TABLE content_items
        ADD COLUMN source_type text
        NOT NULL DEFAULT 'items'
    """)

    op.execute("""
        ALTER TABLE content_items_auto
        ADD COLUMN source_type text
        NOT NULL DEFAULT 'auto'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items_auto', 'source_type')
    op.drop_column('content_items', 'source_type')
    # ### end Alembic commands ###
