"""add sidecar tables for extended metadata

Revision ID: eb4d0ebbd211
Revises: b5a355d7e4da
Create Date: 2025-10-20 13:38:48.164594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from genonaut.db.schema import JSONColumn


# revision identifiers, used by Alembic.
revision: str = 'eb4d0ebbd211'
down_revision: Union[str, Sequence[str], None] = 'b5a355d7e4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items_auto_ext',
    sa.Column('source_table', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('metadata_more', JSONColumn(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_items_auto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('content_items_ext',
    sa.Column('source_table', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('metadata_more', JSONColumn(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_items_ext')
    op.drop_table('content_items_auto_ext')
    # ### end Alembic commands ###
