"""

Revision ID: ec47a6ae1d27
Revises: af8ac3ad61c2
Create Date: 2025-10-16 14:19:51.064640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec47a6ae1d27'
down_revision: Union[str, Sequence[str], None] = 'af8ac3ad61c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_search_history_user_created', 'user_search_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_user_search_history_user_id'), 'user_search_history', ['user_id'], unique=False)
    op.drop_index(op.f('idx_content_tags_tag_source_content'), table_name='content_tags')
    op.drop_table_comment(
        'content_tags',
        existing_comment='Junction table for many-to-many relationship between content and tags',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'content_tags',
        'Junction table for many-to-many relationship between content and tags',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_content_tags_tag_source_content'), 'content_tags', ['tag_id', 'content_source', 'content_id'], unique=False)
    op.drop_index(op.f('ix_user_search_history_user_id'), table_name='user_search_history')
    op.drop_index('idx_user_search_history_user_created', table_name='user_search_history')
    op.drop_table('user_search_history')
    # ### end Alembic commands ###
